"""add client_credentials composite index

Revision ID: 346a227157d9
Revises: 20241031_0002
Create Date: 2025-11-09 18:24:48.082212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '346a227157d9'
down_revision: Union[str, None] = '20241031_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_client_credentials_client_env_access_exp', 'client_credentials', ['client_id', 'environment', 'access_expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_client_credentials_client_env_access_exp', table_name='client_credentials')
    # ### end Alembic commands ###
